spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

SecretJwtString=${JWT_SECRET}

server.port=${PORT:10000}
server.address=0.0.0.0

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect