spring.datasource.url=jdbc:mysql://localhost:3306/monisha_inventory
spring.datasource.username=root
spring.datasource.password=pass

SecretJwtString=yzSh2J2ieRbvwCayyO5pK63640yKJzKrlSn7hXOH0d4H9cE9lrssQSCPk53EsjUWec4527Vl7896IoUeMhTC+A==