spring.datasource.url=jdbc:mysql://monisha-inventory-system-database-monisha-inventory-system-back.e.aivencloud.com:18554/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ZcHrHXF1duPlF2VOwR5

SecretJwtString="tinashegomo123gomotinashe321"