spring.application.name=MonishaInventoryManagementSystem

spring.profiles.active=${SPRING_PROFILE:local}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

SecretJwtString=${JWT_SECRET}

server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true



