spring.application.name=MonishaInventoryManagementSystem

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/monisha_inventory
spring.datasource.username=root
spring.datasource.password=pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

SecretJwtString="tinashegomo123456789tinashegomo123456789";
